#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the stones function below.
def stones(n, a, b):
    a,b=min(a,b),max(a,b)
    if a==b:
        c=[]
        c.append((n-1)*a)
        return(c)
    c=[0]
    for i in range(n-1):
        x=c[-1]
        c=[int(i+a) for i in c]
        c.append(int(x+b))
    return c
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    T = int(input())

    for T_itr in range(T):
        n = int(input())

        a = int(input())

        b = int(input())

        result = stones(n, a, b)

        fptr.write(' '.join(map(str, result)))
        fptr.write('\n')

    fptr.close()




#This code will solve all your problems. It is easy to understand.
